name: Fetch latest blog posts
on:
  schedule: # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: "4"
          remove_duplicates: true
          # feed_list: "https://dev.to/feed/aris,https://jurnalog.com/rss.xml"
          feed_list: "https://jurnalog.com/rss.xml,https://riipandi.medium.com/feed"
