name: GitLab Sync

on:
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync Repo to GitLab
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        # Such as https://gitlab.com/riipandi/riipandi.git
        target-url: ${{ secrets.GITLAB_TARGET_URL }}
        target-username: ${{ secrets.GITLAB_TARGET_USERNAME }}
        # You can store token in your project's 'Setting > Secrets'
        # and reference the name here. Such as ${{ secrets.GITLAB_TOKEN }}
        target-token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
